### ISSUE TITLE
RSPEC-2259 and Null Dereferencer

### ISSUE THREAD

**Issue by JaedenRuiner** [SonarSource/sonar-dotnet#1301]
### Description

I use the C# 6.0 Null-Dereferencer (?.) a lot.  It appears that with recent updates to the analyzer it had resolved most of those issues.  However, not all.
If you are retrieving a sub property of an Object by way of the Null-Dereferencer and test that resulting value for null, subsequent access to the Object can never be null at that point.
![image](https://user-images.githubusercontent.com/36714687/38175491-c2f97da4-35a2-11e8-861d-1dcf96b03106.png)

### Repro steps

My scenario involves DataTable and DataRow.

1. Load Data into a DataTable.
    DataTable table = new DataTable();
    table.Load(sqlDataReader);
2. Assign a local DataRow row variable 
    ie: table?.Rows[0];
3. Test row for null
    ie: if (row != null) { }
4. Access the table variable from within the scope of the if compound statement.
    table.Columns[0];

### Expected behavior

It should recognize that there is no way for table to be null if "row" is not null.

### Actual behavior
It does not make that logical deduction.

### Known workarounds

Ignore it or excessively test the row and table variables.

### Related information

* SonarC# Version: 6.8 (approx)
* Visual Studio Version 2015 Enterprise (14.~)

**Comment by valhristov** [comment]
This is a limitation of the current implementation of the analyzer. I will try to elaborate.

If we have the following code:

```
var row = table.Rows[index];
```

from this point on, on all subsequent lines, `table` will have `NotNull` constraint because otherwise this line would have thrown `NullReferenceException`. Note that we will not raise issues when you dereference `table` like this, unless you test it for `null` beforehand.

The case is different with your code, though:

```
var row = table?.Rows[index];
```

this code will not throw `NullReferenceException` and we won't apply `NotNull` constraint on `table`. The `null` test happens after this line where we already lost the knowledge that `row` is related to `table` and when `row` has `NotNull`, `table` should have it too.

The functionality for the support of `Nullable<T>` could be modified and used for the conditional operators, but it is not a trivial change and for the time being we will not be able to dedicate time to implement it.

**Comment by andrei-epure-sonarsource** [comment]
fixed in #2497
