### ISSUE TITLE
No data reported for ASP.NET Core MVC 2.1 projects OOTB

### ISSUE THREAD

**Issue by nwoolls** [SonarSource/sonar-dotnet#1866]
### Description

Running the SonarScanner on an ASP.NET Core MVC application results in no data (bugs, vulnerabilities, code smells) being reported in the SonarQube UI.

### Repro steps

From a *nix environment:

1. Run `mkdir sonar-csharp-mvcnodata`
1. Run `cd sonar-csharp-mvcnodata`
1. Run `dotnet new mvc`
1. Edit the generated `.csproj` file and specify a `ProjectGuid`
1. Run `dotnet <path-to-scanner> begin [args]`
1. Run `dotnet build`
1. Run `dotnet <path-to-scanner> end [args]`

### Expected behavior

The following code smells should be reported in the SonarQube UI:

* S1118
* S1075

### Actual behavior

The project shows in SonarQube with 0 bugs, 0 vulnerabilities and 0 code smells.

### Known workarounds

Not really a work-around (since it is not viable), but to demonstrate the small change needed to get data to show in the SonarQube UI, do the following (after the initial *Repro steps*):

1. Delete the `Views/` folder

After that, the usual (same) steps will result in the expected code smells showing in the SonarQube UI:

1. Run `dotnet <path-to-scanner> begin [args]`
1. Run `dotnet build`
1. Run `dotnet <path-to-scanner> end [args]`

### Related information

* SonarC# Version: `7.5 (build 6605)`
* SonarScanner Version: `4.3.1`
* SonarQube Version: `6.7.1 (build 35068)`
* .NET Core SDK Version: `2.1.402`
* MSBuild Version: `15.4.0.0`

### Notes
This issue to does not seem to occur with ASP.NET Core MVC 2.0 apps. See https://github.com/SonarSource/sonar-scanner-msbuild/issues/541 for more information.

**Comment by Evangelink** [comment]
Hi @nwoolls,

That's a really weird issue but I do confirm that I can reproduce it using the steps you are describing.

We will have a look to fix this soon.

Cheers,
Amaury

**Comment by duncanp-sonar** [comment]
@nwoolls,

The issue is that the ASP.NET targets call the CSC compiler task twice if there are Razor files to be compiled.
The "normal" .cs files are built and analyzed first, then the Razor .cs files are generated, compiled and analyzed. The analysis report for Razor files overwrites the analysis for the "normal" files, so none of those issues are uploaded to SonarQube. The Razor issues are not reported either because they are recognized as being in generated code.

As a workaround, could you try adding the following XML snippet to your ASP.NET .csproj file and let me know if it works for you please? We'll have to do some more investigation to check whether this workaround has any side-effects on non-ASP.NET projects, but it would be useful to know whether it works in your case.

Thanks,
Duncan

``` 
  <Target Name="DisableCodeAnalysisForRazor"
      Condition=" $(SonarQubeTempPath) != '' "
      AfterTargets="CoreCompile"
      BeforeTargets="RazorCoreCompile">

    <!-- ASP.NET 2.1 core projects that use Razor trigger the CSC compile task a second time.
         We don't want code analysis to run on that generated code since it will overwrite
         the results from the first invocation of CSC.
    -->
    <CallTarget Targets="WriteSonarQubeProjectData" />

    <PropertyGroup>
      <ErrorLog></ErrorLog>
      <ResolvedCodeAnalysisRuleset></ResolvedCodeAnalysisRuleset>
    </PropertyGroup>
    
    <ItemGroup>
      <!-- Clear the original set of analyzers and additional files -->
      <Analyzer Remove="@(Analyzer)" />
      <AdditionalFiles Remove="@(AdditionalFiles)" />
    </ItemGroup>
    
  </Target>
```

**Comment by nwoolls** [comment]
@duncanp-sonar I can confirm that the proposed work-around does work. Would this impact Sonar's ability to analyze `.cshtml` files for bugs / issues / etc.?

**Comment by Evangelink** [comment]
Will be handled through #627
