### ISSUE TITLE
Enable security hotspot rules in ITs automatically

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-dotnet#1934]
#### WHY?
The security hotspots are enabled only when their ID is present in SonarLint.xml, which is created by Scanner for MSBuild. Our C# ITs don't use Scanner for MSBuild but have a hardcoded [SonarLint.xml](https://github.com/SonarSource/sonar-csharp/blob/master/sonaranalyzer-dotnet/its/SonarLint.xml). When adding new security hotspot rules we need to manually update the aforementioned file.

#### WHAT
We need to develop automatic hotspot enabling when the ITs are run so that we don't forget to execute the rules.

**Comment by vit-svoboda** [comment]
I spent quite a lot of time wondering why one of the SonarQube analyzers doesn't surface issues where it should while others work perfectly. Eventually, I dug through the source codes of the package and found out the ruleset/`.editorconfig` doesn't apply to a few select rules because of reasons.

I'm guessing the NuGet package is not supposed to be consumed directly?

**Comment by pavel-mikula-sonarsource** [comment]
Ahoj @vit-svoboda,

Consuming NuGets directly is one of the supported alternatives, if you don't use SonarCloud/SonarQube. But security hotspots are not supposed to be triggered during standalone NuGet analysis.

Security hotspots have a special separated flow in SonarCloud/SonarQube, because they aren't issues but hotspots. In general, they raise noisy warnings that aren't always actionable, because the warning can be reviewed as safe in SC/SQ. This isn't easily possible with NuGet (except suppressions) and you might have a lot of warnings that are not actionable.

You can provide `SonarLint.xml` additional analysis file in your `*.csproj`/`*.vbproj` file to enable those rules. But please be aware of their nature and prepare a plan how to handle those cases that will be reviewed as safe. Getting used to the raised warnings is not a good practice.
