### ISSUE TITLE
Rule S2077: Update rule by detecting only formatted or concatenated strings

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [SonarSource/sonar-dotnet#2394]
We want the rule to not raise when we know nothing of the SQL string parameter, ex: when it comes from a method argument and has no assignation in the method itself.
```
void execQuery(string query, String value)
{
  SqlCommand command;
  command = new SqlCommand(query); // OK because no concatenation or formatting
  command = new SqlCommand(string.Concat(query, value)) // Sensitive
}
```

The code block in the *Exceptions* remain valid.

**Note that the rule's message has also been updated.**

**Comment by duncanp-sonar** [comment]
@nicolas-harraudeau-sonarsource I think it would be better if the _Exceptions_ block contained a bit more information to make help users understand why this is exception is valid. Currently, it's easy to miss that this exception only applies to specific methods Entity Framework, and only because the framework added special handling for this case.

As it is, I think there is a risk that users either won't believe the exception because it doesn't sound right, or will incorrectly think it means using string interpolation protects against SQL injection in all cases.

Suggestions: refer the Entity Framework in the text of the exception, and include a link to the Entity Framework documentation for the user to follow to learn more (e.g. https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0#string-interpolation-in-fromsql-and-executesqlcommand - there may be a better link).

**Comment by nicolas-harraudeau-sonarsource** [comment]
@duncanp-sonar I updated the RSPEC. Thanks for your suggestion.
