### ISSUE TITLE
Improve CFG for `try` statement: fix `break` and `continue` inside `try` inside `loop`

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2550]
When the `try` contains a `continue` or `break`, the shape of the CFG is quite wrong.

Example 1
```
            var attempts = 0;
            do
            {
                cw0();
                try
                {
                    attempts++;
                    cw1();
                    break;
                }
                catch(Exception e)
                {
                    cw2();
                }
            } while (true);
            cw5();
```
Actual: The `try` block has edges to `catch`, `while` and `afterWhile`. 
Expected: The `try` block should have an edge to `catch` and one to `break` (no edge to `while` because of the `break`) and the `break` block should have an edge to `afterWhile`, and the `catch` should have an edge to `while`.

First case: try-catch, no finally. Relevant UTs:
- [`Cfg_TryCatch_WithBreak_Inside_DoWhile`](https://github.com/SonarSource/sonar-dotnet/blob/fa3b0d04988973f7a48312bc81eadeeab9960bc6/sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs#L2723)
- [`Cfg_TryCatch_Inside_DoWhile_WithThrow_InsideCatch`](https://github.com/SonarSource/sonar-dotnet/blob/fa3b0d04988973f7a48312bc81eadeeab9960bc6/sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/ControlFlowGraph/ControlFlowGraphTest.cs#L2935)

Next step: consider `finally` statements inside loops  #474

**Comment by christophe-zurn-sonarsource** [comment]
Further investigation of this ticket yielded the following results:

There are actually several issues with CFG generation when jump statements (`return`, `break`, `continue`) are mixed with loops and `try-catch-finally` statements. Reusing `Example 1` shown above:
```
var attempts = 0;
do
{
  cw0();
  try
  {
    attempts++;
    cw1();
    break;
  }
  catch(Exception e)
  {
    cw2();
  }
} while (true);
cw5();
```

1. when a `break` statement is found inside a `try`, 2 `BranchBlock` elements are generated for the try: 1 is a dangling block without any predecessor, having `catch` and `while` successors. The other is the one correctly plugged in the CFG, but having `catch`, `while` and `afterWhile` successors, which is also wrong as it should not have the `while` as a successor.

2. Only the last block of the try body is linked to the `catch`. When the body of a try contains several CFG blocks, it can lead to incorrect issues. Example:
```
            var attempts = 0;
            var bool = attempts > 1;
            string str = "";
            do
            {
                cw0();
                try
                {
                    if (bool) {
                       str = null;
                       doSomethingThatThrows();
                    }
                    str = "";
                    cw1();
                    break;
                }
                catch(Exception e)
                {
                    str.Trim();
                }
            } while (true);
            cw5();
```
In the above example, the try body is comprised of an `if-branchNode` having 2 successors: `if-body` and `after-if`. Since it does not have the catch as a potential successor, it cannot detect that `str` can be null in the catch block.

3. The above example raises the question of which blocks should have `catch` as potential successors: all the blocks in the try body? If so, all blocks inside will become `BranchBlock`

4. try statements with `return` statements are also incorrectly mapped: the instructions inside the try body, before the `return` statement, are actually inside the return `JumpBlock`, and the `try` block is branching between the `catch` and `return` block. This causes FP. Example:
```
var attempts = 0;
            do
            {
                try
                {
                    attempts++; // FP - dead store as the branching `try` block does not see this instruction before the catch, as the instruction is incorrectly inside the return block
                    DoNothing();
                    return;
                }
                catch (Exception ex)
                {
                    if (attempts > retries)
                        throw;
                }
            } while (true);
```

**Comment by andrei-epure-sonarsource** [comment]
Thanks @christophe-zurn-sonarsource  - due to the complexity of the necessary changes, we will probably need to do a sprint only on improving the CFG representation of the `try`.

**Comment by andrei-epure-sonarsource** [comment]
Adding another reproducer from #2691
```
    public class Repro2691
    {
        public void Method()
        {
            foreach (var item in new List<string>())
            {
                bool warning = false;
                try
                {
                    if (DateTime.UtcNow >= DateTime.Now)
                    {
                        warning = true; // Noncompliant FP
                        continue;
                    }

                    Console.WriteLine("do something else.");
                }
                catch (Exception)
                {

                    throw;
                }
                finally
                {
                    // do something with the `warning` variable
                    Console.WriteLine(warning);
                }
            }
        }
    }
```

**Comment by andrei-epure-sonarsource** [comment]
@pavel-mikula-sonarsource is this still relevant with the new Roslyn CFG?

**Comment by pavel-mikula-sonarsource** [comment]
No, all of those are properly supported by now
