### ISSUE TITLE
Investigate why S2259 does not always trigger on C# 8 code

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2601]
### Description

C#8 introduces the concept of non-nullable reference types. By default, the reference types are considered non-nullable. See details in [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#nullable-reference-types). 

I analyzed andrei-epure-sonarsource/CSharp8Demo [on SonarCloud](https://sonarcloud.io/dashboard?id=Cs8Demo). Note [that the csproj](https://github.com/andrei-epure-sonarsource/CSharp8Demo/blob/master/CSharp8Demo/CSharp8Demo.csproj) has the `NullableContextOptions` enabled.

Rule [S2259](https://rules.sonarsource.com/csharp/RSPEC-2259) doesn't behave normally with easy-to-find cases.

### Repro steps

Look at [this line on sonarcloud](https://sonarcloud.io/code?id=Cs8Demo&line=17&selected=Cs8Demo%3ACSharp8Demo%2F06_NullableReferenceTypes.cs). It is clearly a NRE (and it does thrown at runtime).

### Expected behavior

The analyzer should raise S2259 at line 17, 20, 25 and 42.

### Actual behavior

Only line 42 has a raised issue.

### Known workarounds

None.

### Related information

* SonarC# Version 7.16

**Comment by christophe-zurn-sonarsource** [comment]
While digging into the reasons the issues are not raised for C#8, I found 2 causes:

1. CFG generation fails when it encounters a null-forgiving operator (ex: `str!.Length`), as code will go inside `CSharpControlFlowGraphBuilder#BuildExpression(ExpressionSyntax expression, Block currentBlock)`, and the expression has type `SuppressNullableWarningExpression`, which is not known => method will throw a `NotSupportedException`. To fix this, we should use an updated Shim layer that defines correctly the `SuppressNullableWarningExpression` kind inside the`SyntaxKindEx` class, as well as update the logic inside `BuildExpression` to handle this type of syntax node correctly.

2. Unrelated to C#8, but SE engine exploration stops on the first null dereference found (due to [this line here](https://github.com/SonarSource/sonar-dotnet/blob/ff7413922f6565eccccda028d0d89f22d2a11c68/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/NullPointerDereference.cs#L241)). So for the analyzer to raise an issue on each of the dereference found in the [example code](https://sonarcloud.io/code?id=Cs8Demo&selected=Cs8Demo%3ACSharp8Demo%2F06_NullableReferenceTypes.cs) referenced above, we should either put them in separate methods, or continue the SE after the first issue found.

**Comment by pavel-mikula-sonarsource** [comment]
We need to add test cases and then we'll see what the behavior of the new engine is

**Comment by ckasabula** [comment]
Our team is seeing this issue. I am unable to view the sources referenced in this thread.

Any update on this?

See the following example.

`    public static class Example
    {
        public class Test
        {
            public string Uri { get; set; }
        }

        public static void Omg()
        {
            // change just one of these member accesses on the lines commented w/ S2259 to use null conditional operator and it suppresses all other occurrences of S2259 warning in the method 
            int[] ia = null;
            Console.WriteLine(ia.Length); // S2259
            Test[] ta = Array.Empty<Test>();
            var test1 = ta.FirstOrDefault();
            Console.WriteLine(test1.Uri); // S2259
            Test test2 = null;
            Console.WriteLine(test2.Uri); // S2259
        }
    }`

**Comment by ckasabula** [comment]
A single null coalescing will suppress all S2259 warnings in a method too.

**Comment by ckasabula** [comment]
We are dotnet 6.0 / C# 10.

**Comment by pavel-mikula-sonarsource** [comment]
We're in process of rewriting our Symbolic Execution engine. We'll revisit this once the effort is done. That should happen later this year.

**Comment by martin-strecker-sonarsource** [comment]
Related issue #4250 for the new engine.

**Comment by sebastien-marichal** [comment]
@andrei-epure-sonarsource Do you think this issue can be closed?
