### ISSUE TITLE
Curiosity about analysis of all project files.  

### ISSUE THREAD

**Issue by saamanthacosta** [SonarSource/sonar-dotnet#3082]
I have some rules that need an information collector. This collector saves all the files in the project that will be analyzed. This way, in my rules, I can check if a file is a View and if this file only access the Service or Domain (all the same layer of the View). 

In Java, i had a PreScanner that used to analyze all the files, and the information collector was called in this file. I don't know where I can do this on this plugin.

**Comment by andrei-epure-sonarsource** [comment]
hi @saamanthacosta 

First, we have a dedicated category on [our community forum](https://community.sonarsource.com/c/plugins/customrules/18) for plugin development, please open a topic there as I will close this one (we use github issues just for issues that will be eventually fixed in this repository - bugs, false positives).

Secondly, you can [read this answer](https://community.sonarsource.com/t/how-are-the-rules-for-visual-studio-designed/2699/2) regarding rule development in C#.

Third, writing a custom plugin for C# implies developing a Roslyn analyzer, so I suggest you check out:
- [Roslyn Wiki](https://github.com/dotnet/roslyn/wiki/How-To-Write-a-C%23-Analyzer-and-Code-Fix)
- [Read the tutorial from Microsoft](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix)

Good luck!
