### ISSUE TITLE
Fix possible NRE in CSharpControlFlowGraphBuilder

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3156]
### Description

See this [sonarcloud bug issue](https://sonarcloud.io/project/issues?id=sonaranalyzer-dotnet&open=AXAbMHQ1o9K0T9AzRkIa&resolved=false&types=BUG) for a NRE detected in `sonaranalyzer-dotnet/src/SonarAnalyzer.CFG/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs`

![NRE](https://user-images.githubusercontent.com/38876598/75137766-c114f900-56e8-11ea-9c52-120628de46b3.JPG)

### Related information

* SonarC# Version 8.14

**Comment by pavel-mikula-sonarsource** [comment]
@andrei-epure-sonarsource Are you sure we want to fix this? 

Deep inside, it's actually a FP in this case. It would require `switchStatement.Sections` collection to contain null. And that should not happen (AFAIK). And we usually don't trigger on foreach member to be null. So this warning seems to be caused only by the way we've implemented SE engine (because there's explicit null check before foreach).

Whatever I do in the code will be only a workaround to please our SE implementation with readability/maintainability penalty.

I would just mark it as "won't fix" and document this FP as won't fix in the test.

**Comment by andrei-epure-sonarsource** [comment]
I agree, it's an FP in this particular case as we know the collections from rolsyn won't contain null
