### ISSUE TITLE
Optional parameters should not be used rule is deprecated by Microsoft Roslyn

### ISSUE THREAD

**Issue by mitchello** [SonarSource/sonar-dotnet#3622]
### Description

By reviewing activated rules for our analyses, I have faced an interrogation. Does the rule "Optional parameters should not be used" should be applied for controllers in C#, does it make sens?

After a few research, I have found that Roslyn has deprecated similar [rule](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1026?view=vs-2019), as well as [others](https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-unported-deprecated-rules?view=vs-2019).

Since this rule is deprecated by Microsoft (without any [explanation ](https://github.com/dotnet/roslyn-analyzers/issues/626)), is the rule "Optional parameters should not be used" still relevant?

Thank in advance for you answer.

Regards.

**Comment by markusschaber** [comment]
I guess the rule is deprecated as all relevant compilers now support optional parameters with default values. This used to be different a long time ago.

**Comment by costin-zaharia-sonarsource** [comment]
Hi @mitchello and @markusschaber, thanks for your feedback!

I think this rule is still useful for library authors in the context of backwards compatibility. 

We can use the following snippet as an example:

```
public class Person
{
    public string FirstName { get; }

    public string LastName { get; }

    public Person(string firstName, string lastName)
    {
        FirstName = firstName;
        LastName = lastName;
    }
}
```

Let's assume that the first library version will have similar class, with a constructor with 2 parameters: `Person(string firstName, string lastName)`.

Then, in the next one, a new optional parameter is added: `Person(string firstName, string lastName, string zipCode = null)`

The code will compile just fine but if we try to run old client code with a new version of the library it will fail since the method with 2 parameters no longer exist:

```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void Lib.Person..ctor(System.String, System.String)'.
   at Client.Program.Main(String[] args)
```

**Comment by markusschaber** [comment]
If you're doing a major release, binary compatibility is not required according to semantic versioning.
Also, if the method contains the optional parameters from the beginning, it's also fine.

So your argument of backwards compatibility only makes sense when the rule actually compares both versions of the API, and I'm not aware that sonar-dotnet is capable of doing this. (If it is, I know several rules I'd like to have in that context. :-) )

**Comment by costin-zaharia-sonarsource** [comment]
> If you're doing a major release, binary compatibility is not required according to semantic versioning.

Even if it's required or not between releases it can still give a bad surprise if the code compiles but fails at runtime; so one might prefer to avoid optional parameters in specific cases.

**Comment by andrei-epure-sonarsource** [comment]
Given the rule is not part of the default quality profile, it makes sense to keep it for those cases where users find it useful and will activate it.
