### ISSUE TITLE
S2234 Improve performance: ParametersCorrectOrder

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3765]
S2234 ParametersCorrectOrder calls the symbol very early in the analysis. We should consider whether there is a better way, if we can defer this by relying on the AST before using the SemanticModel.

From this [investigation](https://community.sonarsource.com/t/re-net-analysis-time-during-msbuild-increased-from-15-min-to-40-min/32956/3), the rule takes  2%.

>23.038    2      SonarAnalyzer.Rules.CSharp.ParametersCorrectOrder

**Comment by martin-strecker-sonarsource** [comment]
The issue was probably already fixed by #8238 
The MethodParameterLookup (which queries for symbols) now happens only if there are at least two arguments where a name can be inferred.

@andrei-epure-sonarsource, can we close the issue? #8238 was a complete rewrite of the rule, and the investigation results no longer apply.
