### ISSUE TITLE
S3253: Add exception for rule if there is xml-comment for class member

### ISSUE THREAD

**Issue by anreton** [SonarSource/sonar-dotnet#4606]
### Description

[S3253](https://rules.sonarsource.com/csharp/RSPEC-3253)

The constructor that the compiler generates has no xml-comment, which stands out from the general coverage of the code by xml-comments.

### Repro steps

```csharp
public class Foo
{
    /// <summary>
    /// Initializes a new instance of the <see cref="Foo"/> class.
    /// </summary>
    public Foo()
    {
    }
}
```

### Expected behavior

No diagnostic for S3253, if there is xml-comment for class member.

### Actual behavior

Get diagnostic for S3253, if there is xml-comment for class member.

### Related information

- Microsoft Visual Studio Community 2019 Version 16.10.2
- SonarAnalyzer.CSharp 8.24.0.32949 via Nuget

**Comment by csaba-sagi-sonarsource** [comment]
Hi @anreton 

I am not sure I understand why you think that this is an issue? The rule states that the constructor will be generated automatically by the compiler, so it is a waste of keystrokes to have it. Does adding a comment makes the constructor non redundant?

I would take a step back and reconsider if it is worth writing a part of code + document just for pleasing a tool. If there is some low coverage issue because of the auto generated constructor I would say the issue is in the tool that creates the coverage report.

**Comment by anreton** [comment]
@csaba-sagi-sonarsource, yes, I think this is a very fair point of view.

Anyway, thanks for your reply.
