### ISSUE TITLE
NRE in ReferenceEqualityCheckWhenEqualsExists with 8.25.0.33663

### ISSUE THREAD

**Issue by Piedone** [SonarSource/sonar-dotnet#4641]
### Description

When building a large and complex project I get the following error:

```
CSC : error AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.ReferenceEqualityCheckWhenEqualsExists' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. 
```

### Repro steps

This issue is not present with 8.24.0.32949 but is with 8.25.0.33663.

Unfortunately, I can't share the whole codebase publicly. One of the projects that throw the error is this one: https://github.com/Lombiq/Helpful-Libraries/tree/orchard-core-preview/Lombiq.HelpfulLibraries.RestEase (I've selected the smallest one). If necessary, I can give access to the codebase privately after some paperwork. I'm sorry I can't share more.

Also, it seems that the error goes away on subsequent builds.

Might be related to https://github.com/SonarSource/sonar-dotnet/issues/4567 but that bug report predates 8.25.0.33663.

### Known workarounds

Downgrading to 8.24.0.32949.

### Related information

* C#/VB.NET Plugins version: not using the plugin.
* Visual Studio version: 16.10.3
* MSBuild / dotnet version: 5.0.301
* SonarScanner for .NET version (if used): 8.25.0.33663
* Operating System: Windows 10 20H2 build 19042.1083

**Comment by pavel-mikula-sonarsource** [comment]
Hi @Piedone,

This issue is exactly the same as the #4567 that you've found. It's not even related to our analyzer version, but to the underlying Roslyn version/.NET SDK.

Please add your voice to the [thread](https://github.com/dotnet/roslyn/issues/53943) we've reported to Roslyn so they can prioritize this fix.

This issue is known to be nondeterministic so it disappears on consequent runs and it's hard to reproduce.

**Comment by Piedone** [comment]
Ah I see, thank you!
