### ISSUE TITLE
S3358 can be reworded to recommend replacing them with tuple based switch expressions.

### ISSUE THREAD

**Issue by AraHaan** [SonarSource/sonar-dotnet#4735]
Because switch expressions are a thing, I think the best course of action with S3358 is that instead of telling them to extract them to independent statements that it instead has this as the warning message:

```warning S3358: This nested ternary operation can be converted into a tuple based switch expression.```

With a codefix that can then convert them into a tuple based switch expression.

Example:

```cs
_ = temp.Append(!output_format_md ? tabs ? "\t+ " : "    + " : "+ ");
```

Fixed:

```cs
_ = temp.Append((!output_format_md, tabs) switch
{
    (true, true) => "\t+ ",
    (true, false) => "    + ",
    _ => "+ ",
});
```

In this case ``temp`` is a ``StringBuilder``.

cc @pavel-mikula-sonarsource, @costin-zaharia-sonarsource

**Comment by dmitry-golovinov-sonarsource** [comment]
Hey @AraHaan , thanks for leaving us a feedback. Among other ideas we have to improve the existing engine exists one, that is called _Improve code fix providers to create modern patterns instead of old-style code_. I've just added this issue to that task, so it could be considered and worked on as a part of this effort.

**Comment by AraHaan** [comment]
Alright, thanks.

**Comment by pavel-mikula-sonarsource** [comment]
Hi, I'm not sure this will play nicely for more nested scenarios.
```
_ = temp.Append(firstCase ? ";" ? secondCase ? ComputeSomethingComplicated() ? !output_format_md ? tabs ? "\t+ " : "    + " : "+ ");
```
