### ISSUE TITLE
Improve S1244: Add message to use "IsX" instead of "== double.X"

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonar-dotnet#6521]
### Description

S1244 (Floating point numbers should not be tested for equality) complains about a comparison like this
```cs
if (d == double.NaN) // Noncompliant {{Do not check floating point equality with exact values, use a range instead.}}
{ }
```

In this case, the message should read: `Do not check floating point equality with exact values, use double.IsNaN()` instead.

The following methods should be supported:
* [INumberBase<TSelf>.IsNaN(TSelf) Method (System.Numerics) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.inumberbase-1.isnan?view=net-7.0)
* ~~[INumberBase<TSelf>.IsFinite(TSelf) Method (System.Numerics) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.inumberbase-1.isfinite?view=net-7.0)~~
* ~~[INumberBase<TSelf>.IsInfinity(TSelf) Method (System.Numerics) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.inumberbase-1.isinfinity?view=net-7.0)~~
* [INumberBase<TSelf>.IsNegativeInfinity(TSelf) Method (System.Numerics) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.inumberbase-1.isnegativeinfinity?view=net-7.0)
* [INumberBase<TSelf>.IsPositiveInfinity(TSelf) Method (System.Numerics) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.inumberbase-1.ispositiveinfinity?view=net-7.0)

For backward compatibility below .Net 7 double and float should be supported directly.

**Comment by antonioaversa** [comment]
After discussing with @pavel-mikula-sonarsource, the following changes to the issue:
- `with exact values` used in the messages for `NaN`, `PositiveInfinity` and `NegativeInfinity`, instead of the text `with special values`: any special value (namely constants defined in well-known floating-point types before .NET 7, and `static abstract` properties `IFloatingPointIeee754<TSelf>` since .NET 7) is also an exact value (such as `1.0`, `2.3f`, ...).
- `INumberBase.IsInfinity` and `INumberBase.IsFinite` are methods checking multiple floating point values (IsInfinity checks for both `PositiveInfinity` and `NegativeInfinity`, `IsFinite` checks for zero and for all normal and subnormal values). As such they don't fall into the category of `== Something`, and are considered out of scope for this task. 

Conversely, `== type.IsNaN()`, `== type.IsPositiveInfinity()` and `== type.IsNegativeInfinity()` all have corresponding constant or properties, and are considered in scope.
