### ISSUE TITLE
Fix S4581 FP: Does not work with constant value passed to constructor

### ISSUE THREAD

**Issue by PhenX** [SonarSource/sonar-dotnet#6892]
### Description

The rule `S4581: Use 'Guid.NewGuid()' or 'Guid.Empty' or add arguments to this GUID instantiation.` gives a false positive when the parameter is a constant string.

### Repro steps

Use `new Guid(Foo)` where Foo is a constant

### Expected behavior

Do not report this case as an issue

### Actual behavior

![image](https://user-images.githubusercontent.com/42170/224061994-1446e219-dfea-4ef1-9769-feab8ab255b4.png)

### Known workarounds

No workaround

### Related information

* C# dotnet analyzer version 8.54.0.64047
* JetBrains Rider 2022.3.2
* Dotnet SDK 7
* Operating System : Windows 11

**Comment by mary-georgiou-sonarsource** [comment]
Hello @PhenX,
Thank you for opening this issue. Your feedback helps us improve our products.

In this case, an issue is raised because the `const string PublicId` is the default Guid value `00000000-0000-0000-0000-000000000000` - that you can also set by calling  `Guid.Empty`.
If you replace the value of your const variable with something else - the issue won't be raised anymore.

IMO, this is not an FP.
