### ISSUE TITLE
New rule S6576: Use `DateOnly` or `TimeOnly` instead of setting just date or time for a `DateTime` class

### ISSUE THREAD

**Issue by csaba-sagi-sonarsource** [SonarSource/sonar-dotnet#7082]
Implement new rule [S6576: Use DateOnly or TimeOnly instead of setting just date or time for a DateTime class](https://github.com/SonarSource/rspec/pull/1730).

This rule should raise when a new `DateTime` object is created and only the time or date properties are set.

- [ ] Implement Rule S6576 for C#
- [ ] Implement Rule S6576 for VB.NET

**Comment by cristian-ambrosini-sonarsource** [comment]
I'm closing this RSPEC PR and the related [rule implementation PR](https://github.com/SonarSource/sonar-dotnet/pull/7472).
The rule is dropped due to the high FP rate it can generate. 
Some are reported in the test script within this PR and marked with the comment `// Noncompliant FP`.
Looking at DateOnly and TimeOnly usage in [SourceGraph](https://sourcegraph.com/search?q=context:global+new+DateOnly%28+file:%5C.cs%24++count:all+select:file+&patternType=standard&sm=0&groupBy=repo) we didn't manage to define a specific pattern to create a rule with significant TP rate.
To cover all the cases the rule would be very complicated and not cost-effective.
