### ISSUE TITLE
sonar.cs.roslyn.reportFilePaths and sonar.cs.analyzer.projectOutPaths don't support glob pattern

### ISSUE THREAD

**Issue by leolcao** [SonarSource/sonar-dotnet#7181]
Hi SonarSource team, thanks for the great work for the SonarScanner for .NET plugin firstly.

I am working on the way to use sonar-scanner for c# and vc++ projects at same time, so the formal pattern:

```
dotnet-sonarscanner begin ...

dotnet build|test ...

dotnet-sonarscanner end ...
```
is not work as I expected.

Now, I found a workaround, just use `dotnet-sonarscanner begin ...`, and not use `dotnet-sonarscanner end. ..`, so I can get the Sonar Roslyn Analyzer result files under the folder `.sonarqube/out/xxx`.

and I have to write my own sonar-project.properties with the analysis parameters `sonar.cs.analyzer.projectOutPaths` and `sonar.cs.roslyn.reportFilePaths`

But, I find these 2 parameters don't support wildcards like: `.sonarqube/out/*`, `.sonarqube/out/**/Issues.json`, obviously I want to let the content simple and no update efforts any more.

I know this is a kind of 'hacking' to bypass the formal usage, but this way solve my requirements ~

**Comment by antonioaversa** [comment]
Hi @leolcao, thanks for opening this issue. 
We will look into the issue and come back to you as soon as possible.

**Comment by csaba-sagi-sonarsource** [comment]
@leolcao 

First of all, thank you for reaching out to us!
However, this is the wrong repository, the problem seems to be related to the [scanner for dotnet](https://github.com/SonarSource/sonar-scanner-msbuild). The guides in that repository say to open a [community topic](https://community.sonarsource.com/) instead of reporting issues in the repository.

So, I would kindly ask you to open a new topic and describe what you want to achieve. It might be that there is a different non "hacky" solution to your problem.

**Comment by leolcao** [comment]
Thanks for the information! I will looking for help from the community ~
