### ISSUE TITLE
UtilityAnalyzer: Reduce lock contention in `ShouldGenerateMetrics`

### ISSUE THREAD

**Issue by csaba-sagi-sonarsource** [SonarSource/sonar-dotnet#7411]
https://github.com/SonarSource/sonar-dotnet/pull/6576 introduced a performance regression that was reverted in https://github.com/SonarSource/sonar-dotnet/pull/7262. Our investigation showed the cause of the regression was that using the `RegisterSemanticModelAction` changed the behaviour of the analyzer to a multithreaded approach. `ShouldGenerateMetrics` queries the `UnchangedFilesCache` and calls `GeneratedCodeRecognizer.IsGenerated`. As both are based on synchronized collections it creates a thread contention which caused the performance regression.
The idea is to precalculate the generated and unchanged files and in the SemanticModelAction only use the values. In theory, this should remove the thread contention, enabling us to introduce one again the changes made in https://github.com/SonarSource/sonar-dotnet/pull/6576.

**Comment by martin-strecker-sonarsource** [comment]
Other things to look at:
* HasGeneratedCodeAttribute: Is there a reason why we call `DescendantNodesAndSelf` (walking the entire tree) instead of `ChildNodes`?
* Why `attributeName.EndsWith`? `GetAttributeName` should give the unqualified name.
* Why is `IsGenerated` not called via `SyntaxTreeExtensions.IsGenerated` (which caches) by UtilityAnalyzers? Should we make the method uncallable or inline the caching to make it impossible to call the uncached version? It is e.g. also called by the `ClassAndMethodName` analyzer.

We may need to split the issue before we work on it.

**Comment by martin-strecker-sonarsource** [comment]
Another root cause might be the queuing of the tasks for the SyntaxTree registration. It might also help to enable concurrent analyzes. This requires the Analyzers to be stateless. See #7288 and #6674.

**Comment by martin-strecker-sonarsource** [comment]
The contention on `IsGenerated` can be seen in the profiling here:
![image](https://github.com/SonarSource/sonar-dotnet/assets/103252490/c30a0ad9-fe34-47ff-a247-87c33dcf1144)
