### ISSUE TITLE
Fix S3247 FN: alias any type

### ISSUE THREAD

**Issue by cristian-ambrosini-sonarsource** [SonarSource/sonar-dotnet#8121]
The rule does not take into account when using alias directive to alias tuple types, array types, pointer types, or other unsafe types.

```cs
using Person = (string name, string surname);

class MyClass
{
    void AliasType(Person person)
    {
        var a = (Person)person; // FN
    }
}
```

**Comment by antonioaversa** [comment]
The example given:
```cs
using Person = (string name, string surname);

class MyClass
{
    void AliasType(Person person)
    {
        var a = (Person)person;
    }
}
```
is not supposed to raise [S3247](https://sonarsource.github.io/rspec/#/rspec/S3247), because it's not a duplicated cast.

A minimal case of duplicated cast is the following:
```cs
using Person = System.String; // (string name, string surname);

class AClass
{
    void Test(object obj)
    {
        if (obj is Person) // Noncompliant
        {
            var a = (Person)obj; // Secondary
        }
    }
}
```

That example works when using the C# 12 "Alias any type": `using Person = string;`.
```cs
using Person = string; // Alias any type

class AClass
{
    void Test(object obj)
    {
        if (obj is Person) // Noncompliant
        {
            var a = (Person)obj; // Secondary
        }
    }
}
```

It is true that `using Person = (string name, string surname);` doesn't work:
```cs
using Person = (string name, string surname);

class AClass
{
    void Test(object obj)
    {
        if (obj is Person) // FN
        {
            var a = (Person)obj;
        }
    }
}
```

However, this is not a C# 12 issue related to alias any type. It is rather an issue that happens due to `ValueTuple` being a `struct`, and it actually happens with any struct:

```cs
void Test(object obj)
{
    if (obj is Person) // FN
    {
        var a = (Person)obj;
    }
}

struct Person { }; // If struct is replaced with class, it's not a FN anymore.
```

The problem with extending this rule to struct is that `as` cannot be used with value types:
```cs
void Test(object obj)
{
    var a = obj as Person; // CS0077 The as operator must be used with a reference type or nullable type
    if (a != null)
    {
        // Use a...
    }
}

struct Person { }; 
```

We could suggest using pattern matching: `if (obj is Person a)`, but that is already captured by an existing issue in the backlog: https://github.com/SonarSource/sonar-dotnet/issues/2120.

So I would propose to close this issue, as it's not C#12 related, and maybe consider the inclusion of https://github.com/SonarSource/sonar-dotnet/issues/2120 in a hardening sprint (or even in the current sprint, if time is left).

**Comment by antonioaversa** [comment]
> Agreed. At this point, we should remove the `// FN` comment on the reproducer, and maybe add an example with a struct alias and reference it to #2120.

I have created [this PR](https://github.com/SonarSource/sonar-dotnet/pull/8259) to add the repro. 

I picked #223 instead of #2120 since it seems more appropriate and general.

I have mentioned #2120 in #223 and viceversa.
