### ISSUE TITLE
Rule S1125: Boolean literals should not be redundant

### ISSUE THREAD

**Issue by rruggiere** [SonarSource/sonar-dotnet#8147]
### Description
I don't believe that this issue remains on new syntax available on C#9. In discussions about good practices a good point lifted up by a developer is how much hidden is the denying operator when you read some code like this:
if(!isValid)
   doSomething()
This sounds like a easter egg in the code and to write something like
if(isValid is false)
   doSomething()
Is a lot more readable cause it's clear what the logic you are passing. When we enable sonar on our solutions this code smell exploded on our softwares but we believe this should be reviewed. Why is it considered bad practice?
Please provide a succinct description of your issue. Also please provide the rule ID (e.g. S1234)

* C#/VB.NET Plugins version

**Comment by antonioaversa** [comment]
Hi @rruggiere, thanks for reporting this issue.

After your report, we had a very interesting internal discussion about [S1125](https://sonarsource.github.io/rspec/#/rspec/S1125/csharp). 

It turns out that, when `is` pattern was introduced with C# 7, users asked us to report on them, the same way we report on `==`-based comparison. 
See for example [this issue](https://github.com/SonarSource/sonar-dotnet/issues/2619) reported in 2019, that was implemented [earlier this year](https://github.com/SonarSource/sonar-dotnet/pull/7687). [Here](https://github.com/SonarSource/sonar-dotnet/issues/7688) is another issue reported internally.

The diverging opinion on the matter seems to come from the fact that `b is false` feels more readable than `b == false`, because `b is false` is English, whereas `b == false` is not. `b is true`, on the other hand, seems as "bad" as `b == true`, because there is a better, shorter, more readable option: `b`.

So, for the time being, at least, we can't simply exclude `is false` from this rule without disappointing some users.

In the longer term, we are planning to run a specification effort and explore multiple options here:
1. keep the rule as is
1. extract the `is false` and `is true` checks from S1125, and create a second rule for those
1. option 2, but only reporting on `is false` (i.e. `is true` would be acceptable)
1. three different rules
1. ...  

I have created [a new issue](https://github.com/SonarSource/sonar-dotnet/issues/8178) in our backlog, to identify the best approach. It will be included in one of our next hardening sprints, we can't commit however when that will happen.

I am closing this issue. For the time being:
- you can mark the issue as a false-positive in the UI of SonarQube or SonarCloud. The rule can also be disabled in your Quality Profile by an administrator if it gets particularly noisy.
- you can use `#pragma warning disable` and `#pragma warning restore` to locally disable the rule in the source. You can also use the `.editorconfig` files to disable or change the severity of the rule if it gets particularly noisy.
