### ISSUE TITLE
Reduce allocation during registration by SonarSyntaxNodeReportingContext

### ISSUE THREAD

**Issue by sebastien-marichal** [SonarSource/sonar-dotnet#8425]
About 20% of our allocation happens during `RegisterNodeAction`.

![image](https://github.com/SonarSource/sonar-dotnet/assets/126669183/bba25486-ec7f-414d-8523-4a33baf1ba2b)

This is due to instantiating the SonarSyntaxNodeContext over and over.

One possible solution is to replace our context classes with structs (we are not ready 😬)

**Comment by martin-strecker-sonarsource** [comment]
A typical allocation contribution for a scanner run looks like so:
![image](https://github.com/SonarSource/sonar-dotnet/assets/103252490/46e77126-2d7a-4292-a1bb-8e818bb6ff74)
The crossed-out allocations were caused by the `IsMatch` implementation in the security frontend (fixed by now) and can be ignored. `SonarSyntaxNodeReportingContext` is the top allocating type, responsible for ~10% of the overall allocations of the entire compilation. The next biggest allocation caused by `Symbol[]` is four times smaller than `SonarSyntaxNodeReportingContext`

**Comment by sebastien-marichal** [comment]
Duplicate of [#8877](https://github.com/SonarSource/sonar-dotnet/issues/8877)
