### ISSUE TITLE
New Rule S6966: Awaitable method should be used

### ISSUE THREAD

**Issue by zsolt-kolbay-sonarsource** [SonarSource/sonar-dotnet#9096]
RSPEC: https://github.com/SonarSource/rspec/pull/3854

**Comment by jilles-sg** [comment]
This rule may be useful to complete the final parts of an migration to async or to help prevent incorrect sync calls being added. However, there are cases where a normally asynchronous (I/O) type is synchronous, such as `MemoryStream`, `StringReader`, `StringWriter` or a `StreamWriter` that writes to a `MemoryStream`. In such cases, the asynchronous calls are unnecessary overhead. This is particularly nasty when `await using` has to be used with `.ConfigureAwait(false)`, since a separate variable is required to store the `ConfiguredAsyncDisposable`.
