### ISSUE TITLE
Vulnerability issue due to Google.Protobuf (CVE-2021-22570)

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [SonarSource/sonar-dotnet#9660]
Hi,

could you please upgrade dependency to Google.Protobuf to latest one
![image](https://github.com/user-attachments/assets/038d50c6-7c66-4dd6-b05c-d823b47d1c60)

 due to 
https://www.mend.io/vulnerability-database/CVE-2021-22570

![image](https://github.com/user-attachments/assets/67d26de1-418b-4208-8d28-09874fb0b4db)

unfortunatelly it is reported by Mend
![image](https://github.com/user-attachments/assets/defbeaf2-0ba0-4e7f-b307-ac03912aeb9c)

**Comment by pavel-mikula-sonarsource** [comment]
Hi @AdaskoTheBeAsT,

We can not, unfortunately, because the new version does not work well on .NET Framework environments, causing the analysis (build time) to slowdown by dozens of minutes, or hours in some cases.

The CVE finding in our analyzer is a False Positive, because the analyzer doesn't deserialize any protobuf files. So you are not at any risk.
